import assert from "node:assert/strict";
import fs from "node:fs";
import {buildCashbackProgramEditorModel,renderCashbackProgramEditor} from "../services/cashback-program-config.js";
const cards=[{id:"A"},{id:"B"}],programs=[{id:"A1",cardId:"A",name:"A One",rate:.05,max:200000,allMcc:true},{id:"B1",cardId:"B",name:"B One",rate:.05,max:200000,allMcc:true}];
const model=buildCashbackProgramEditorModel({cards,programs,selection:{cardId:"B",programId:"A1"}});
assert.equal(model.selectedProgram.id,"B1");
const html=renderCashbackProgramEditor(model,{escape:String,formatMoney:String,mccOptions:()=>"",transactionMethodOptions:()=>""});
assert.equal(html.includes("A One"),false);
assert.equal(html.includes("B One"),true);
const css=fs.readFileSync(new URL("../styles.css",import.meta.url),"utf8");
assert.match(css,/\.cashback-program-selectors\{/);
assert.match(css,/\.cashback-program-layout\{/);
console.log("cashback program workflow UI tests passed");
