import assert from "node:assert/strict";
import {exportCashbackProgramRows,importCashbackProgramRows} from "../services/cashback-program-excel.js";
const mccCategories=[{id:"FOOD",name:"Ăn uống",mcc:"5812"}];
const programs=[{id:"P1",cardId:"CARD",name:"Ăn uống",year:2026,month:9,rate:.05,max:200000,maxCashbackUnlimited:false,eligibleSpendMinimum:1000000,allMcc:false,mccCategoryIds:["FOOD"],channel:"Online",note:"Keep"}];
const context={mccCategories,cards:[{id:"CARD"}],existingPrograms:programs};
const rows=exportCashbackProgramRows(programs,context);
assert.equal(rows.length,1);
assert.equal(rows[0]["Program ID"],"P1");
assert.equal(rows[0]["Tên chương trình"],"Ăn uống");
assert.equal(Object.hasOwn(rows[0],"Tên điều kiện"),false);
const imported=importCashbackProgramRows(rows,context);
assert.equal(imported.length,1);
assert.equal(imported[0].id,"P1");
assert.equal(imported[0].name,"Ăn uống");
assert.equal(imported[0].rate,.05);
assert.deepEqual(imported[0].mccCategoryIds,["FOOD"]);
assert.equal(Array.isArray(imported[0].conditions),false);
const legacy=[{"Năm":2026,"Tháng":9,"Card ID":"CARD","Group ID":"LEGACY","Tên nhóm":"Legacy","Condition ID":"LC","Tên điều kiện":"Legacy child","% CB":"5%","Max CB":200000,"Mã MCC":"5812"}];
assert.equal(importCashbackProgramRows(legacy,context)[0].name,"Legacy child");
console.log("cashback program Excel tests passed");
