import assert from "node:assert/strict";
import {calculateSpendToMax} from "../services/cashback.js";
import {buildCashbackProgramEditorModel,renderCashbackProgramEditor,renderCashbackProgramPage,renderCashbackProgramStructure} from "../services/cashback-program-config.js";

const helpers={escape:String,formatMoney:String,calculateSpendToMax,mccOptions:()=>"<option>Tất cả</option>",transactionMethodOptions:()=>"<option>Tất cả</option>"};
const cards=[{id:"CARD-A"},{id:"MB Pla"}];
const programs=[{id:"P1",cardId:"CARD-A",name:"Ăn uống",rate:.05,max:200000,allMcc:true},{id:"P2",cardId:"CARD-A",name:"Mua sắm",rate:.03,max:100000,allMcc:true},{id:"MB1",cardId:"MB Pla",name:"Ăn uống",packageId:"DAILY",rate:.05,max:200000,allMcc:true}];
const model=buildCashbackProgramEditorModel({cards,programs,selection:{cardId:"CARD-A",programId:"P1"}});
const html=renderCashbackProgramEditor(model,helpers);
assert.match(html,/data-add-program[^>]*>\+ Thêm chương trình/);
assert.match(html,/data-condition-name[^>]*value="Ăn uống"/);
assert.match(html,/Tên chương trình/);
assert.doesNotMatch(html,/Tên điều kiện|Thêm điều kiện|ĐIỀU KIỆN CASHBACK/);
assert.equal((html.match(/data-condition-name/g)||[]).length,1);
assert.match(html,/data-condition-rate[^>]*value="5\.0"/);
assert.match(html,/data-condition-spend-to-max[^>]*value="4000000"/);
assert.doesNotMatch(html,/data-program-name/);
const structure=renderCashbackProgramStructure(model,helpers);
assert.match(structure,/Thẻ: CARD-A/);
assert.match(structure,/1\. Ăn uống/);
assert.match(structure,/2\. Mua sắm/);
assert.equal(renderCashbackProgramPage(model,helpers).includes("cashback-program-layout"),true);

const mbModel=buildCashbackProgramEditorModel({cards,programs,cashbackCardConfigs:[{cardId:"MB Pla",statementMinSpend:5000000}],selection:{cardId:"MB Pla",programId:"MB1"}});
const mbHtml=renderCashbackProgramEditor(mbModel,helpers);
assert.match(mbHtml,/data-program-package-id/);
assert.match(mbHtml,/Hàng ngày/);
assert.match(mbHtml,/Phong cách sống/);
assert.match(mbHtml,/data-card-statement-min[^>]*value="5000000"/);
console.log("cashback program editor tests passed");
