import assert from "node:assert/strict";
import {exportCashbackProgramRows,exportCashbackTransactionAssignments,importCashbackCardConfigs,importCashbackProgramRows,importCashbackTransactionAssignments} from "../services/cashback-program-excel.js";
const cards=[{id:"MB Pla"}],config={cardId:"MB Pla",statementMinSpend:5000000,rotationAnchorPeriodKey:"statement:2026-08-21:2026-09-20",rotationAnchorPrimaryPackageId:"LIFESTYLE"};
const programs=[{id:"DAILY-FOOD",cardId:"MB Pla",name:"Ăn uống",packageId:"DAILY",year:2026,month:9,rate:.05,max:200000,allMcc:true},{id:"LIFE-FOOD",cardId:"MB Pla",name:"Ăn uống",packageId:"LIFESTYLE",year:2026,month:9,rate:.05,max:200000,allMcc:true}];
const rows=exportCashbackProgramRows(programs,{mccCategories:[],cashbackCardConfigs:[config]});
assert.deepEqual(rows.map(row=>row["Program ID"]),["DAILY-FOOD","LIFE-FOOD"]);
assert.deepEqual(rows.map(row=>row["Package ID"]),["DAILY","LIFESTYLE"]);
assert.equal(rows[0]["Mức chi tối thiểu kỳ sao kê"],5000000);
assert.equal(rows[0]["Kỳ neo luân phiên"],config.rotationAnchorPeriodKey);
assert.equal(rows[0]["Gói chính tại kỳ neo"],"LIFESTYLE");
const imported=importCashbackProgramRows(rows,{cards,mccCategories:[]});
assert.deepEqual(imported.map(item=>[item.id,item.packageId,item.name]),[["DAILY-FOOD","DAILY","Ăn uống"],["LIFE-FOOD","LIFESTYLE","Ăn uống"]]);
assert.deepEqual(importCashbackCardConfigs(rows,cards),[config]);
const transactions=[{id:"TX",cardId:"MB Pla",cashbackPackageId:"DAILY",cashbackProgramId:"DAILY-FOOD"},{id:"LEGACY",cardId:"MB Pla"}];
const transactionRows=exportCashbackTransactionAssignments(transactions);
assert.deepEqual(transactionRows[0],{"ID":"TX","Cashback Package ID":"DAILY","Cashback Program ID":"DAILY-FOOD"});
assert.deepEqual(importCashbackTransactionAssignments(transactionRows,transactions)[0],transactions[0]);
assert.deepEqual(importCashbackTransactionAssignments([{"ID":"LEGACY"}],transactions)[1],{...transactions[1],cashbackPackageId:"",cashbackProgramId:""});
console.log("MB Platinum Excel tests passed");
